
#             /$$$$$$$$$$$$|
#            |____  $$____/
#     /$$   /$$   | $$     /$$$$$$   /$$$$$$  /$$$$$$/$$$$   /$$$$$$$
#    |  $$ /$$/   | $$    /$$__  $$ |____  $$| $$_  $$_  $$ /$$_____/
#     \  $$$$/    | $$   | $$$$$$$$  /$$$$$$$| $$ \ $$ \ $$|  $$$$$$
#      >$$  $$    | $$   | $$_____/ /$$__  $$| $$ | $$ | $$ \____  $$
#     /$$/\  $$   | $$   |  $$$$$$$|  $$$$$$$| $$ | $$ | $$ /$$$$$$$/
#    |__/  \__/   |__/    \_______/ \_______/|__/ |__/ |__/|_______/  by Drygo

#   Github page: https://github.com/xDrygo/xTeams - X: https://x.com/eldrygo

# Welcome to the configuration file of the plugin xTeams. Here you can modify some plugin settings.

# List of teams and the list of players in the team.
hooks:
  luckperms:
    enabled: false
    team_groups: # [xTeams team]: <LuckPerms group>
      blue: blue
      red: red
      yellow: yellow
  minecraft_team:
    enabled: false
    team_groups: # [xTeams team]: <Minecraft team>
      blue: blue
      red: red
      yellow: yellow
  auto_team:
    enabled: false
    op_bypass: false
    team: red
teams:
  red:
    displayName: "&e&lRed Team"
    priority: 2
    members:
      - player1
      - player2
  blue:
    displayName: "&e&lBlue Team"
    priority: 1
    members:
      - player3
      - player4
  yellow:
    displayName: "&e&lYellow Team"
    priority: 0
    members:
      - player5
      - player6