name: xTeams
version: 0.0.36
main: org.eldrygo.XTeams
api-version: 1.21
authors: [Drygo]
softdepend: [PlaceholderAPI]
commands:
  xteams:
    description: "Plugin main command"
    subcommands:
      create:
        description: "Creates a new team."
      delete:
        description: "Deletes a team."
      join:
        description: "Joins a team."
      leave:
        description: "Leaves a team."
      list:
        description: "Lists all teams."
      info:
        description: "Displays information about a team."
      reload:
        description: "Reloads the plugin configuration and message files."
      save:
        description: "Saves the plugin data to the configuration files."
permissions:
  xteams.command:
    description: "Allows users to execute xTeams commands"
    default: false
    children:
      xteams.command.base: true
      xteams.command.create: true
      xteams.command.delete: true
      xteams.command.join: true
      xteams.command.leave: true
      xteams.command.info: true
      xteams.command.list: true
      xteams.command.reload: true
      xteams.command.save: true
  xteams.admin:
    description: "Allows administrators to execute xTeams commands"
    default: false