name: xTeams
version: 1.2.2
main: org.eldrygo.XTeams.XTeams
api-version: 1.20
authors: [Drygo]
softdepend: [PlaceholderAPI]
commands:
  xteams:
    description: "Plugin main command"
permissions:
  xteams.command:
    description: "Allows users to execute xTeams commands"
    default: false
    children:
      xteams.command.create:
        default: false
      xteams.command.delete:
        default: false
      xteams.command.delete.all:
        default: false
      xteams.command.setdisplay:
        default: false
      xteams.command.join:
        default: false
      xteams.command.leave:
        default: false
      xteams.command.leave.all:
        default: false
      xteams.command.info:
        default: false
      xteams.command.teaminfo:
        default: false
      xteams.command.playerinfo:
        default: false
      xteams.command.list:
        default: false
      xteams.command.reload:
        default: false
      xteams.command.help:
        default: false
  xteams.admin:
    description: "Allows administrators to execute xTeams commands"
    default: false