name: xTeams
version: 1.3.1
main: dev.drygo.XTeams.XTeams
api-version: 1.20
authors: [Drygo]
softdepend:
  - PlaceholderAPI
  - LuckPerms
commands:
  xteams:
    description: "Plugin main command"
permissions:
  xteams.admin:
    description: "Allows administrators to execute xTeams commands"
    default: false
    children:
      xteams.command.create:
        default: false
      xteams.command.delete:
        default: false
      xteams.command.delete.all:
        default: false
      xteams.command.setdisplay:
        default: false
      xteams.command.join:
        default: false
      xteams.command.leave:
        default: false
      xteams.command.leave.all:
        default: false
      xteams.command.info:
        default: false
      xteams.command.sync:
        default: false
      xteams.command.teaminfo:
        default: false
      xteams.command.playerinfo:
        default: false
      xteams.command.list:
        default: false
      xteams.command.reload:
        default: false
      xteams.command.help:
        default: false